version: '3.1'

services:

  card-dock-base-api:
    build: .
    environment:
      MYSQL_CONNECTION: 'Server=mysql18;Port=3306;Database=HackaDB;Uid=root;Pwd=admin'
    ports:
      - '8001:80'

  mysql:
    image: mysql:8.0.16
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - 3306:3306
    container_name: mysql18


  